// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoftServe.ITAcademy.BackendDubbingProject.Administration.Infrastructure.Database;

namespace Web.Migrations
{
    [DbContext(typeof(DubbingContext))]
    [Migration("20200812110110_InitialCreate2")]
    partial class InitialCreate2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("SoftServe.ITAcademy.BackendDubbingProject.Administration.Core.Entities.Audio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Duration");

                    b.Property<string>("FileName")
                        .IsRequired();

                    b.Property<int>("LanguageId");

                    b.Property<string>("OriginalText")
                        .IsRequired();

                    b.Property<int>("SpeechId");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("SpeechId");

                    b.ToTable("Audio");
                });

            modelBuilder.Entity("SoftServe.ITAcademy.BackendDubbingProject.Administration.Core.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("SoftServe.ITAcademy.BackendDubbingProject.Administration.Core.Entities.Performance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Performances");
                });

            modelBuilder.Entity("SoftServe.ITAcademy.BackendDubbingProject.Administration.Core.Entities.Speech", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Duration");

                    b.Property<int>("Order");

                    b.Property<int>("PerformanceId");

                    b.Property<string>("Text")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("PerformanceId");

                    b.ToTable("Speeches");
                });

            modelBuilder.Entity("SoftServe.ITAcademy.BackendDubbingProject.Administration.Core.Entities.Audio", b =>
                {
                    b.HasOne("SoftServe.ITAcademy.BackendDubbingProject.Administration.Core.Entities.Language", "Language")
                        .WithMany("Audios")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SoftServe.ITAcademy.BackendDubbingProject.Administration.Core.Entities.Speech", "Speech")
                        .WithMany("Audios")
                        .HasForeignKey("SpeechId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SoftServe.ITAcademy.BackendDubbingProject.Administration.Core.Entities.Speech", b =>
                {
                    b.HasOne("SoftServe.ITAcademy.BackendDubbingProject.Administration.Core.Entities.Performance", "Performance")
                        .WithMany("Speeches")
                        .HasForeignKey("PerformanceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
